# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID')),
                ('item_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Item_Name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('hsn_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='HSN_Code')),
                ('source_file', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Source_File')),
                ('xref', models.CharField(blank=True, max_length=255, null=True, verbose_name='XREF')),
                ('fuzzy_deduplication_comment', models.TextField(blank=True, null=True, verbose_name='Fuzzy_Deduplication_Comment')),
                ('fuzzy_deduplication_reason', models.TextField(blank=True, null=True, verbose_name='Fuzzy_Deduplication_Reason')),
                ('fuzzy_deduplication_candidates', models.TextField(blank=True, null=True, verbose_name='Fuzzy_Deduplication_Candidates')),
                ('ai_recommendation', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI Recommendation')),
                ('ai_reason', models.TextField(blank=True, null=True, verbose_name='AI Reason')),
                ('ai_confidence', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI Confidence')),
                ('ai_suggested_values', models.TextField(blank=True, null=True, verbose_name='AI Suggested Values (JSON)')),
                ('is_active', models.BooleanField(default=True, help_text='False if merged into another record')),
                ('is_reviewed', models.BooleanField(default=False, help_text='True if record has been reviewed')),
                ('merged_info', models.TextField(blank=True, help_text='Log of merge history', null=True)),
            ],
            options={
                'verbose_name': 'Data Record',
                'verbose_name_plural': 'Data Records',
            },
        ),
    ]
