# Generated by Django 6.0.1 on 2026-02-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steward", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="is_merged",
            field=models.BooleanField(
                default=False, help_text="True if record was created/updated via merge"
            ),
        ),
    ]
